### ISSUE TITLE
Call to undefined method: "isFullyQualified()"

### ISSUE THREAD

**Issue by voku** [icanhazstring/composer-unused#1]
php7.2 /usr/bin/composer global require icanhazstring/composer-unused

```
Using version ^0.1.0 for icanhazstring/composer-unused
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing nikic/php-parser (v4.2.1): Loading from cache
  - Installing icanhazstring/composer-unused (0.1.0): Downloading (100%) 
```

php7.2 /usr/bin/composer unused

```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::isFullyQualified() in /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/Strategy/StaticParseStrategy.php:25
Stack trace:
#0 /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/NodeVisitor.php(34): Icanhazstring\Composer\Unused\Parser\Strategy\StaticParseStrategy->meetsCriteria(Object(PhpParser\Node\Stmt\Expression))
#1 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Icanhazstring\Composer\Unused\Parser\NodeVisitor->enterNode(Object(PhpParser\Node\Stmt\Expression))
#2 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#4 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114 in /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/Strategy/StaticParseStrategy.php on line 25

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::isFullyQualified() in /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/Strategy/StaticParseStrategy.php:25
Stack trace:
#0 /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/NodeVisitor.php(34): Icanhazstring\Composer\Unused\Parser\Strategy\StaticParseStrategy->meetsCriteria(Object(PhpParser\Node\Stmt\Expression))
#1 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Icanhazstring\Composer\Unused\Parser\NodeVisitor->enterNode(Object(PhpParser\Node\Stmt\Expression))
#2 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#4 /home/lmoelleken/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114 in /home/lmoelleken/.composer/vendor/icanhazstring/composer-unused/src/Parser/Strategy/StaticParseStrategy.php on line 25
```

**Comment by icanhazstring** [comment]
Hi @voku thanks for using the lib. Can you give me more information about the project you used it with? If it's public maybe I can try it out.

And maybe I should implement some kind of exception handling where or which file the exception occurred during scanning.

**Comment by voku** [comment]
Noop, sorry! It's a legacy customer project but when I use ```strace php7.2 /usr/bin/composer unused``` I can see that the next file is the source of the problem "https://gist.github.com/voku/6ca2740380d87f22b82fc2a4c09b5503" ... it wasn't used in the codebase anyway, so I deleted it :P

**Comment by icanhazstring** [comment]
So it kinda worked 😅.
Anyway this tool needs a better debug mode 😉
