### ISSUE TITLE
ServiceManager (Zend) not found in container.php (0.6.0)

### ISSUE THREAD

**Issue by bestog** [icanhazstring/composer-unused#56]
**Describe the bug**
I wanted to install the dependency with `composer require --dev icanhazstring/composer-unused` and afterwards I got the error message that the `Zend\ServiceManager\ServiceManager` was not found. The Dependency was removed with the 0.6.0 release and can therefore no longer be resolved.

**Error dump**
```
PHP Fatal error:  Uncaught Error: Class 'Zend\ServiceManager\ServiceManager' not found in C:\[project]\vendor\icanhazstring\composer-unused\config\container.php:5
Stack trace:
#0 C:\[project]\vendor\icanhazstring\composer-unused\src\UnusedPlugin.php(34): require()
#1 phar://C:/Users/xyz/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(236): Icanhazstring\Composer\Unused\UnusedPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 phar://C:/Users/xyz/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Icanhazstring\Composer\Unused\UnusedPlugin))
#3 phar://C:/Users/xyz/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 phar://C:/Users/xyz/AppData/Local/ComposerSetup/bin/composer.phar/src/Comp in C:\[project]\vendor\icanhazstring\composer-unused\config\container.php on line 5
```

**Comment by icanhazstring** [comment]
Hi @bestog. Thanks for reporting. Will see to it asap. Bugfix coming in soon.

**Comment by bestog** [comment]
@icanhazstring Thank you. 👍
